### ISSUE TITLE
The "Download data" button wrongly redirects to a blank page

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [LaserlikeInc/firefox-addon#11]
**[Affected versions]:**
- Firefox 61.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have the latest Laserlike (0.9.24) version installed on a new Firefox profile.
- Have enough history to have the "For You" section populated. 
- The Laserlike sidebar is opened and you are logged with a valid mail.

**[Steps to reproduce]:**
1. Open browser with the profile from prerequisites.
2. Click the "Settings" button.
3. Click the "Account Settings" button.
4. Click the "Download" button from the Download Data section.
5. Observe the behavior.

**[Expected result]:**
- The Laserlike data is successfully downloaded.

**[Actual result]:**
- You are redirected to a blank page.

**[Notes]**
- The issue is also reproducible if you try to download the data from the Laserlike homepage.
- Here is a screen recording of the issue:
![downlod data](https://user-images.githubusercontent.com/19226534/43208057-27beb2ba-9032-11e8-9a91-4c5b45581856.gif)

**Comment by sg-laserlike** [comment]
This is fixed in the latest build.

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using latest Laserlike (0.9.26) version and the issue is no longer reproducible. Tested on Windows 7 x64, Mac 10.13 and Arch Linux.
