### ISSUE TITLE
After editing the entered email you are wrongly redirected to the "Account Settings" page

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [LaserlikeInc/firefox-addon#19]
**[Affected versions]:**
- Firefox 61.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have the latest Laserlike (0.9.24) version installed on a new Firefox profile.
- The Laserlike sidebar is opened.

**[Steps to reproduce]:**
1. Open browser with the profile from prerequisites.
2. Click the "..." button from one of the displayed story.
3. Click the "Account Settings" button. 
4. Click the "Sign In" button.
5. Enter a wrong mail and click the "Continue" button.
6. Click the "Edit Email" button and enter a valid mail.
7. Click the "Continue" button and observe the behavior.

**[Expected result]:**
- The email is successfully edited and the "Confirm Your Email" section is displayed.
- The confirmation code is successfully sent to the valid mail.

**[Actual result]:**
- The "Account Settings" page is displayed.
- The confirmation code is successfully sent to the valid mail.

**[Notes]**
- In the current implementation, if you click the "Sign In" button after the email was edited, the previously entered mail is still displayed in the email field and you need to edit it again. 
- Here is a screen recording of the issue:
![edited mail](https://user-images.githubusercontent.com/19226534/43261417-46403fac-90e5-11e8-8237-99035851673b.gif)

**Comment by sg-laserlike** [comment]
We fixed this from Laserlike server side, please retest.

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using the latest Laserlike (0.9.32) version and the issue is no longer reproducible. Tested on Windows 7 x64, Mac 10.13 and Arch Linux.
