### ISSUE TITLE
The Feedback button is not displayed after you install the add-on and navigate to a website

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [LaserlikeInc/firefox-addon#21]
[Affected versions]:
- Firefox 61.0.1 and above

[Affected platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open the Firefox browser and navigate to the "about:addons" page -> Extensions section.
2. Install the latest Laserlike addon (version 0.9.24).
3. Navigate to a website (eg. https://www.wikipedia.org/).
4. Observe the bottom part of the Laserlike sidebar.

[Expected result]:
- The "Feedback" button is displayed in the left part.

[Actual result]:
- The "Feedback" button is not displayed.

[Notes]:
- This issue is no longer reproducible if you switch/reopen the sidebar -> navigate to a different website -> close/reopen again the sidebar.
- Here is a screen recording with this issue:
![laser like - feedback button](https://user-images.githubusercontent.com/31244235/43264276-459cdfde-90ee-11e8-8c60-c32f77fee502.gif)

**Comment by itsneal** [comment]
This is actually implemented per the interaction guidelines here, where they survey button should appear after a user triggers the experiment three times - https://github.com/mozilla/testpilot/blob/341a04e2cbece78adf52ab1f8a5ddb6a2b3be4fb/docs/examples/feedback-buttons.md

However, we actually wouldn't mind changing it to be visible immediately upon first use. @chuckharmston thoughts?

**Comment by sg-laserlike** [comment]
Okay we changed this from our server side. The feedback button will show up once installed. Please retest.

**Comment by Softvision-CristinaBadescu** [comment]
I have verified this issue and it is no longer reproducible using the latest "Advance - Powered by Laserlike" v0.9.41. Tested on Windows 10 x64, Mac 10.13.6 and Arch Linux 4.12.
Thanks!
