### ISSUE TITLE
The "Account Settings" page is wrongly displayed for a brief moment after you sign out

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [LaserlikeInc/firefox-addon#23]
[Affected versions]:
- Firefox 61.0.1 and above

[Affected platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the latest Laserlike (0.9.24) version installed on a new Firefox profile.
- Have the Laserlike sidebar open.
- Be signed in with a valid account.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. From Liserlike sidebar hover the "Settings" button.
3. Click the "Account Settings" button.
4. Click the "Sign Out" button  from the "Laserlike Account" section.
5. Observe the behavior.

[Expected result]:
- The "Read Next" and "For You" sections are displayed.

[Actual result]:
- The "Account Settings" page is displayed for a brief moment.

[Notes]:
- Also, if the "For You" section was populated, it is also displayed for a brief moment after you sign out.
- Here is a screen recording with this issue:
![laserlike - sign out](https://user-images.githubusercontent.com/31244235/43264478-fd86605c-90ee-11e8-8ca5-c9e29578c07d.gif)

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue using latest Laserlike (0.9.32) version and the issue is no longer reproducible. Now after signing out, the "Account Settings" page remains open.
Tested on Windows 7 x64, Mac 10.13 and Arch Linux.
