### ISSUE TITLE
The "Account Settings" panel is displayed for a second after starting a new account

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [LaserlikeInc/firefox-addon#28]
[Affected versions]:
- Firefox 61.0.1 and above

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have the latest Laserlike (0.9.24) version installed on a new Firefox profile.
- Have the Laserlike sidebar open.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Hover the Settings gearwheel button.
3. Click the "Account Settings" link.
4. Click the "Delete" links twice.
5. Click the "Start a New Account" link and observe what happens next.

[Expected result]:
- The user is redirected to the articles panel.

[Actual result]:
- The "Account Settings" panel is displayed for a second before the user is redirected to the articles panel. 

[Notes]:
- Attached a screen recording of the issue:

![start new account](https://user-images.githubusercontent.com/26000308/43270891-cebb040c-90fe-11e8-9eca-00877f32a868.gif)

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using the latest Laserlike (0.9.32) version and the issue is no longer reproducible. Tested on Windows 7 x64, Mac 10.13 and Arch Linux.
