### ISSUE TITLE
The "For Your" section wrongly remains stuck in a loading state if it is not populated and the sidebar was switched/reopened

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [LaserlikeInc/firefox-addon#34]
[Affected versions]:
- Firefox 61.0.1 and above

[Affected platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the latest Laserlike (0.9.26) version installed on a new Firefox profile.
- Have the Laserlike sidebar open.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Navigate to "about:addons" page -> "Extensions" section and install the latest Laserlike addon (version 0.0.26).
3. Open a new tab and navigate to a website (eg. https://www.wikipedia.org/).
4. Click the Laserlike toolbar button twice.
5. Observe the "For You" section from the sidebar.

[Expected result]:
- The section is correctly displayed.

[Actual result]:
- A loading spinner is displayed in the section.

[Notes]:
- Sometimes, this issue is no longer reproducible after you switch tabs.
- Also, it seems that the "For You" section is no longer populated. See #33.
- Here is a screen recording with this issue:
![laserlike - for you - loading spinner](https://user-images.githubusercontent.com/31244235/43321783-9ea4c11a-91b5-11e8-818c-75e72b8d9339.gif)

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue using latest Laserlike (0.9.32) version and the issue is no longer reproducible. Tested on Windows 7 x64, Mac 10.13 and Arch Linux.
