### ISSUE TITLE
[Home Page] "Home Page" option is reset and "For You" page is no longer opened in new tab after the account is deleted

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [LaserlikeInc/firefox-addon#39]
[Affected versions]:
- Firefox 61.0.1 and above

[Affected platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have the latest Laserlike (0.9.26) version installed on a new Firefox profile.
- Have the Laserlike sidebar open.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Hover the Settings gearwheel button from the sidebar.
3. Switch to Home Page mode and open a new tab.
4. Hover the Settings gearwheel button from the new tab.
5. Click the "Account Settings" button, then the "Delete" one.
6. Click the "Delete" button again and open a new tab.
7. Observe what happens next.

[Expected result]:
- The Laserlike "For You" page is displayed.

[Actual result]:
- Activity stream new tab is displayed.

[Notes]:
- If you have the Laserlike sidebar opened during the steps above, the "Settings" menu is no longer opened when hovering the gearwheel icon.
- Going back to the previous Laserlike tab and clicking the "Account Settings" button dismisses the menu and prevents opening it again when hovering the gearwheel button.
- Here is a screen recording with this issue:

![home page reset](https://user-images.githubusercontent.com/26000308/43330885-1c35c464-91cd-11e8-81a1-e0a19c29071b.gif)

**Comment by sg-laserlike** [comment]
When account is deleted, the only option allowed is supposed to be "Start a New Account". So the Settings menu shouldn't show up. 

We fixed this from Laserlike server side, please retest.

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using the latest Laserlike (0.9.41) version and the "Settings" menu cannot be accessed while you are on the "Start a New Account" page.
Tested on Windows 7 x64, Mac 10.13 and Arch Linux.
