### ISSUE TITLE
The user seems to be subscribed with "js@mail.com" email while the "Account Settings" page is refreshed

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [LaserlikeInc/firefox-addon#52]
**[Affected versions]:**
- Firefox 61.0.1 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have the latest Laserlike (0.9.26) version installed on a new Firefox profile.
- You are not logged in.
- Have the "Home Page" option enabled from Laserlike menu.

**[Steps to reproduce]:**
1. Open browser with the profile from prerequisites and open a new tab.
2. Hover the "Settings" button and click the "Account Settings" button.
3. Refresh the page and observe the top part of the "Account Settings" menu.

**[Expected result]:**
- The page is correctly refreshed and no onther changes are displayed.

**[Actual result]:**
- While the page is refreshed appears that you are subscribed at js@mail.com.

**[Notes]**
- This issue is only visible on the "Laserlike" homepage.
- The issue is also reproducible after installing the Laserlike add-on on a new Firefox profile.
- Here is a screen recording of the issue:
![wrongly subscribed](https://user-images.githubusercontent.com/19226534/43573404-51f65c18-964a-11e8-9932-7485c2fed0af.gif)

**Comment by sg-laserlike** [comment]
We fixed this from Laserlike server side, please retest.

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue using the latest Laserlike (0.9.41) version and the issue is no longer reproducible. Tested on Windows 7 x64, Mac 10.13 and Arch Linux.
