### ISSUE TITLE
Rename all mentions of the "Laserlike" name to the "Advance" one

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [LaserlikeInc/firefox-addon#56]
Since this experiment will be launched in Test Pilot with the name "Advance", we should change all mentions of the "Laserlike" name into the new one.

Here is a list with the changes that should be made:

- [ ] The icon of the experiment.
- [ ] The name of the add-on that it's displayed in "about:addons" page.
- [ ] The Homepage link displayed in the "about:addons" page.
- [ ] The icon and the name of the experiment that is displayed in the Firefox sidebar menu.
- [ ] The icon and the tooltip of the toolbar button.
- [ ] The title name of the Sidebar.
- [ ] The "Pause Laserlike" option.
- [ ] The description of the "Pause Laserlike" option.
- [ ] The description of the "Downlod Data" section.
- [ ] The "Laserlike Account" section.
- [ ] The description of the "Sign In" page
- [ ] The description of the "Edit Mail" page.
- [ ] The description of the "Delete Account" section from "Account Settings" menu.
- [ ] The description of the "Delete Account" page.
- [ ] The icon displayed in the "Start a New Account" page.
- [ ] The icon displayed in the "Read Next" section when it's not populated.
- [ ] The icon displayed in the "For You" section when it's not populated.
- [ ] The icon displayed in the "Read Next by Laserlike" page.
- [ ] The description of the "Read Next by Laserlike" page.
- [ ] The link of the "Feedback Survey" page.
- [ ] The title of the "Feedback Survey" page.
- [ ] The link of the "Laserlike" homepage (https://feed.laserlike.com/).
- [ ] The title of the "Laserlike" homepage.
- [ ] The link of the "Laserlike" about page (https://feed.laserlike.com/about).

**Comment by sriniven** [comment]
It is Advance, Powered by Laserlike. So we need to keep this as is.

**Comment by sriniven** [comment]
To be clear, we are renaming the extension as "Advance" and in the text
appearance marking it as Advance - Powered by Laserlike.
Lets get the version with that change in and we can review this bug after
that.

**Comment by sriniven** [comment]
All the appropriate places are fixed to say Advance, and in some
appropriate places we keep Laserlike.
Please take a look.

**Comment by SoftVision-CosminMuntean** [comment]
The experiment name and the icon are changed and correctly displayed in the latest (0.9.35) version.
