### ISSUE TITLE
The "selection rectangle" wrongly overlaps the stars from the survey's rating section

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [LaserlikeInc/firefox-addon#61]
[Affected versions]:
- Firefox 61.0.1

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Open the Firefox browser and navigate to the Advance Feedback survey link: https://qsurvey.mozilla.com/s3/advance.
2. Click any star from the rating section and observe the "selection rectangle".

[Expected result]:
- The star is centered in the rectangle.

[Actual result]:
- The rectangle is briefly displayed over the star from the rating section.

[Notes]:
- We also encountered this issue on other experiments, such as [Side View](https://github.com/mozilla/side-view/issues/271) or [Firefox Color](https://github.com/mozilla/FirefoxColor/issues/324).
- The issue is easy to be noticed if you double click one of the stars.
- Here is a screen recording of the issue:
![laserlike - rating stars](https://user-images.githubusercontent.com/31244235/43724652-245903c6-99a3-11e8-9e09-6f958f8db26d.gif)

**Comment by chuckharmston** [comment]
This should be fixed now.
