### ISSUE TITLE
Doesn’t work with First-Party Isolation (FPI)

### ISSUE THREAD

**Issue by da2x** [LaserlikeInc/firefox-addon#66]
Please update all instances of `browser.cookies.getAll()` (and `.get()` and `.set()`) to include `firstPartyDomain: 'feed.laserlike.com'` to make the extension work with First-Party Isolation (go to `about:config` and enable the `privacy.firstparty.isolate` option to test). [MDN docs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/cookies/getAll). `firstPartyDomain` will just have no effect and be ignored if FPI isn’t enabled.

I’m not filing a pull request as the code in the repository is minified. (Where is the actual source code? Surely, you don’t work directly with minified code.)

#### Original report:
I’ve been crusing around the web for hours, but the sidebar keeps displaying “Nothing to see right now.”

The browserAction toolbar icon sometimes shows a green badge with a number on it, but clicking it once just closes the sidebar, and clicking it again opens it again just as void of content.

**Comment by sriniven** [comment]
Thanks for the report, we will take a look.

**Comment by da2x** [comment]
Please note that I updated the original report above with the details on the exact issue and how to fix it.

**Comment by chuckharmston** [comment]
Per @sguo-laserlike, this should be fixed in master.

**Comment by da2x** [comment]
The updated version does indeed work as expected with FPI.
