### ISSUE TITLE
The Laserlike Settings panel is not properly rendered if the sidebar is resized to minimum width

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [LaserlikeInc/firefox-addon#8]
[Affected versions]:
- Firefox 61.0.1 and above

[Affected platforms]:
- All Windows
- All Mac

[Prerequisites]:
- Have the latest Laserlike (0.9.24) version installed on a new Firefox profile.
- Have the Laserlike sidebar open.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Resize the sidebar to minimum width.
3. Hover the "Settings" button.
4. Observe all elements from the displayed panel.

[Expected result]:
- All elements from the "Settings" panel are correctly rendered.

[Actual result]:
- The elements are not properly rendered: the buttons & the email field exceed the panel's margin; the "Pause Laserlike" title overlaps the text that also exceeds the panel.

[Notes]:
- This issue is not reproducible on Arch Linux 4.12.
- Here is a screen recording with this issue:
![laser like - settings panel rendering](https://user-images.githubusercontent.com/31244235/43201112-3ec6a7ae-9020-11e8-8e82-45e3df245715.gif)

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue using latest Laserlike (0.9.26) version and the issue is no longer reproducible. Tested on Windows 7 x64, Mac 10.13 and Arch Linux.
