### ISSUE TITLE
Users may be mislead by the description from "Read Me" section if the "Override DoNotTrack" option is enabled

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [LaserlikeInc/firefox-addon#84]
**[Notes]:**
- In the current behavior the "As you visit sites, we’ll bring you related content here to read next." message is displayed in the "Read Next" section if the "Override DoNotTrack" option is enabled. However, the section is not populated even if you navigate to multiple articles. In order to prevent users from misleading, probably it would be the best if we add a message and explain why the section is not populated or we should hide the "Read Next" section.

**[Affected versions]:**
- Firefox 61.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have the latest Laserlike (0.9.41) version installed on a new Firefox profile.
- Have the Tracking Protection or Do Not Track option enabled.
- Have the "Override DoNotTrack" option is enabled.

**[Steps to reproduce]:**
1. Open browser with the profile from prerequisites.
2. Navigate to "https://www.nytimes.com/" website.
3. Click the "Advance" toolbar icon.
4. Observe the "Read Next" section. 

**[Expected result]:**
- A message that explain why the section is not populated is displayed.
Or
- The "Read Next" section is hidden.

**[Actual result]:**
- The "As you visit sites, we’ll bring you related content here to read next." message is displayed even if the section will not be populated.

**[Additional Notes]**
- Here is a screen recording of the issue:
![rread next section](https://user-images.githubusercontent.com/19226534/44727593-0ef47500-aae3-11e8-9eef-9a3e1a184e80.gif)

**Comment by SoftVision-CosminMuntean** [comment]
I have created a new Advance custom build (v 0.9.45) from the Github repository and I have retested this issue.  It seems that the behavior is a bit changed: 

After you enable the "Override DoNotTrack" option, the "Read Next" section is only populated in the first session while you navigate through different websites.
After the browser is restarted the "Read Next" section is no longer populated while you navigate to different website.
However, if you disable and re-enable  the "Override DoNotTrack" option, the section is again populated until you restart the browser.
Here is a screen recording of the issue: https://goo.gl/hMwmt2

@chuckharmston can you please clarify which is the intended behavrior here? The "Read Next" should be populated while the "Override DoNotTrack" option is enabled?
- If yes, then the issue is that the "Read Next" section is no longer populated after the browser is restarted.
- If not, the issue is that the "Read Next" section is populated in the first session after the  "Override DoNotTrack" option is enabled,

**Comment by sg-laserlike** [comment]
This is fixed as well.
