### ISSUE TITLE
The previously custom options don't persist in a new Private Window after the "Override DoNotTrack" option is enabled

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [LaserlikeInc/firefox-addon#85]
**[Affected versions]:**
- Firefox 61.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have the latest Laserlike (0.9.41) version installed on a new Firefox profile.
- The "Compact Mode" option is disabled.
- The "Home Page" option is enabled.

**[Steps to reproduce]:**
1. Open browser with the profile from prerequisites and open a new Window.
2. Click the "Advance" toolbar icon.
3. Click the "Settings" button from the Advance sidebar.
4. Observe the  "Compact Mode" and "Home Page" options.

**[Expected result]:**
- The "Compact Mode" option is disabled and the "Home Page" one is enabled.

**[Actual result]:**
- The options are reset to the default settings.

**[Notes]**
- If Tracking Protection or DNT option is enabled when you open a Private Window, the "Override DoNotTrack" option is disabled  even if it was enabled in the normal window.
- Here is a screen recording of the issue:
![default settings in pw](https://user-images.githubusercontent.com/19226534/44727718-5d097880-aae3-11e8-8109-e33c9681ddfc.gif)

**Comment by sg-laserlike** [comment]
We don't ever override private window settings. This should be a new feature request.

**Comment by chuckharmston** [comment]
Closing this; it should never work in private browsing mode.
