### ISSUE TITLE
Only the title of the "Read Next" section is displayed after the "Override DoNotTrack" option is enabled or the experiment it's installed

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [LaserlikeInc/firefox-addon#86]
**[Affected versions]:**
- Firefox 61.0.2 and above

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have the latest Laserlike (0.9.41) version installed on a new Firefox profile.

**[Steps to reproduce]:**
1. Open browser with the profile from prerequisites and open a new private.
2. Click the "Advance" toolbar icon.
3. Click the "Settings" button from the Advance sidebar.
4. Enable the "Override DoNotTrack" option.
5. Observe the "Read Next" section. 

**[Expected result]:**
- The entire "Read Next" section is displayed.

**[Actual result]:**
- Only the title of the "Read Next" section is displayed.

**[Notes]**
- The issue is also reproducible if the Tracking Protection or DNT functionality is active and  the "Override DoNotTrack" option is enabled.
- Here is a screen recording of the issue:
![read next title](https://user-images.githubusercontent.com/19226534/44727814-8e824400-aae3-11e8-95a9-e46c2715f1fc.gif)

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue using the latest "Advance" (0.9.45816) version and the issue is no longer reproducible. Tested on Windows 10 x64, Mac 10.13 and Arch Linux.
